### PR TITLE
ENH: Provide a .gitignore file

### PR DESCRIPTION
**Pull request by hjmjohnson**
The gitignore file helps prevent errant files from being included
in the git repository.

### CODE REVIEW

**Comment by tbbdev** [comment]
Hello, Johnson.
Thank you for your contribution. 
We added .gitignore and .gitattributes files into repository and hope that they fit your requirements.
Could you please review them and provide your feedback? Can we close this pull request?

Best regards,
Intel(R) TBB engineering team.

**Comment by hjmjohnson** [comment]
@tbbdev   Where should I review these items?  What branch are they posted under?

Thanks,
Hans

**Comment by tbbdev** [comment]
https://github.com/01org/tbb/blob/tbb_2017/.gitattributes
https://github.com/01org/tbb/blob/tbb_2017/.gitignore

**Comment by hjmjohnson** [comment]
@tbbdev I see. It is just part of the massive all changes for release as-a-patch update. 

This is fine.  Pull request can be closed.

**Pull request closed without merging**
