### PR TITLE
Fix various warnings when building with Visual C++

### PR DESCRIPTION
**Pull request by e4lam**

### CODE REVIEW

**Comment by nik-ponomarev** [comment]
Could you, please, provide an MSVC version where these warnings were found?

**Comment by e4lam** [comment]
Commit 0beb0e2c549f23b0c0733b5243c3083c16ef9b7e I believe originated with Visual Studio 2015 when compiling LTCG enabled on static builds. I'm not sure which service pack anymore but Visual Studio 2015 Update 3 was the last version we used before switching to Visual Studio 2017.

Commit 0ab186b44cdd558677fa702d87bce5891b52810a was on Visual Studio 2017, version 15.Y.X. I'm not sure which 15.Y.X version anymore because of the numerous Visual Studio 2017 updates. It was probably on some latest 15.7.X update.

**Comment by nik-ponomarev** [comment]
Warning fixes for 0beb0e2 is available in the latest [TBB 2019 U1](https://github.com/01org/tbb/releases/tag/2019_U1).
As for 0ab186b, we couldn't reproduce this problem and I think an issue is related to the ussage of parallel_reduce and should be suppressed outside the tbb.

**Comment by hjmjohnson** [comment]
@e4lam Can this issue be closed now. Or the residual work be rebased on top of 2019_U2?

**Comment by e4lam** [comment]
I think it can be closed for now. As I recall the problem showed up with some update of Visual C++ 2017 and building OpenVDB (openvdb.org) with /std:c++14 /permissive- . I'll reopen when I find some time again with exact reproducible steps.

**Pull request closed without merging**
